const mockLargeTextContent = "Explore Wall Street’s expert insights with this ProResearch article, which will exclusively be available to InvestingPro subscribers soon. Dive deeper into the financial world with additional reports now exclusively accessible to Pro subscribers, including in-depth analysis of major players like Pfizer Inc. (NYSE:PFE) (PFE), Shopify (NYSE:SHOP) Inc. (SHOP), Snap Inc (NYSE:SNAP). (SNAP), Accenture plc (NYSE:ACN) (ACN), and Block Inc. (SQ). To ensure ongoing access to valuable content like this, step up your investment game with InvestingPro. Use the coupon PRORE24 to get 10% off a yearly or biyearly Pro and Pro+ subscription. In the fast-paced world of electronic payments, Visa Inc . (NYSE: NYSE:V) stands out as a global leader connecting various entities with its advanced technology. Analysts from esteemed firms have recently provided a comprehensive analysis of Visa's financial health, strategic direction, and market potential. As we delve into the details, it is clear that Visa is navigating the current economic landscape with a strategic eye on growth and shareholder value. Company Overview Visa has been a pioneer in the payments industry, enabling secure and swift transactions across the globe. The company's expansive network connects consumers, businesses, governments, and financial institutions, facilitating a seamless flow of commerce. Visa has consistently demonstrated its ability to adapt and innovate, ensuring its competitive edge in a dynamic market. Financial Performances and Strategy Visa's recent financial results have been robust, surpassing analysts' expectations. The company reported strong fiscal quarter four earnings, with revenue and earnings per share (EPS) beating forecasts. This performance is a testament to Visa's operational efficiency and its ability to capitalize on positive spending trends. Looking ahead, Visa has set an ambitious course for fiscal year 2024, with management reinstating full-year guidance that forecasts double-digit adjusted net revenue growth and low-teens adjusted EPS growth. This guidance is slightly more optimistic than what the buyside anticipated, indicating confidence in the company's strategic initiatives.";

export const mockNews = [
  {
    content: 'By David Lawder and Joel Schectman (Reuters) - Salvage crews were set to lift the first piece of Baltimore"s collapsed Francis Scott Key Bridge from the water on Saturday to allow barges and tugboats to access the disaster site, Maryland and U.S. officials said, the first step in a complex effort to reopen the city"s blocked port.',
    dislikes: 13,
    imageUrl: 'https://i-invdn-com.investing.com/trkd-images/LYNXNPEK2T06K_L.jpg',
    likes: 543,
    publishDate: '31.04.2024',
    source: 'investing.com',
    title: 'Salvage crews to lift first piece of collapsed Baltimore bridge',
    views: 9654,
  },
  {
    content: mockLargeTextContent,
    dislikes: 13,
    imageUrl: 'https://i-invdn-com.investing.com/news/LYNXMPEA7Q0M3_L.jpg',
    likes: 435,
    publishDate: '31.04.2024',
    source: 'investing.com',
    title: 'Pro Research: Wall Street eyes Visa"s growth and resilience',
    views: 6574,
  },
  {
    content: 'EDE, Netherlands, March 30 (Reuters) - A hostage drama at a nightclub in the eastern Netherlands ended peacefully after several hours on Saturday with the arrest of a suspect - a man wearing a balaclava mask who exited the building and surrendered to police.',
    dislikes: 13,
    imageUrl: 'https://www.reuters.com/resizer/v2/https%3A%2F%2Fcloudfront-us-east-2.images.arcpublishing.com%2Freuters%2FQESU34U3NBIY3GRPAETU5GOCEY.jpg?auth=2fb3f2ef19f5cc220a66d797322532a2dad225d214a98694e74c7bcc689034cb&width=1920&quality=80',
    likes: 254,
    publishDate: '31.04.2024',
    source: 'investing.com',
    title: 'Dutch nightclub hostage drama ends peacefully',
    views: 3415,
  },
  {
    content: "(Reuters) -Telecom company AT&T (NYSE:T) said on Saturday that it is investigating a data set released on the 'dark web' about two weeks ago, and said that its preliminary analysis shows it has impacted approximately 7.6 million current account holders and 65.4 million former account holders.",
    dislikes: 13,
    imageUrl: 'https://i-invdn-com.investing.com/trkd-images/LYNXNPEK2T03I_L.jpg',
    likes: 434,
    publishDate: '31.04.2024',
    source: 'investing.com',
    title: 'AT&T says leaked data set impacts about 73 million current, former account holders',
    views: 13424,
  },
  {
    content: 'Explore Wall Street’s expert insights with this ProResearch article, which will exclusively be available to InvestingPro subscribers soon. Dive deeper into the financial world with additional reports now exclusively accessible to Pro subscribers, including in-depth analysis of major players like Pfizer Inc.',
    dislikes: 13,
    imageUrl: 'https://i-invdn-com.investing.com/trkd-images/LYNXNPEK2T06K_L.jpg',
    likes: 26,
    publishDate: '31.04.2024',
    source: 'investing.com',
    title: 'Pro Research: Wall Street delves into Vertex Pharmaceuticals',
    views: 1056,
  },
];
